[pytest]
markers =
    unit: unit-level emulator tests
    regression: generated redis regression tests
    integration: end-to-end emulator integration tests
    sse: sse instructions tests
    mmx: mmx instructions tests
    jump: jump instructions tests
    i686: i686 instructions tests
    fpu: fpu instructions tests
