using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Fiberish.FsName.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class FsNameLiteralGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var literalCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, _) => TryMatchLiteralCall(syntaxContext))
            .Where(static match => match is not null)
            .Select(static (match, _) => match!.Value);

        var compilationAndMatches = context.CompilationProvider.Combine(literalCalls.Collect());
        context.RegisterSourceOutput(compilationAndMatches, static (spc, pair) =>
        {
            EmitRegistrationSource(spc, pair.Left, pair.Right);
        });
    }

    private static LiteralMatch? TryMatchLiteralCall(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
            return null;

        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
        if (symbol is null ||
            symbol.ContainingType.ToDisplayString() != "Fiberish.VFS.FsName" ||
            symbol.Name is not ("FromString" or "FromBytes"))
            return null;

        var arguments = invocation.ArgumentList.Arguments;
        if (arguments.Count is < 1 or > 2)
            return null;

        if (arguments.Count == 2)
        {
            var allowEmpty = context.SemanticModel.GetConstantValue(arguments[1].Expression);
            if (!allowEmpty.HasValue || allowEmpty.Value is not bool boolValue || boolValue)
                return null;
        }

        var literal = symbol.Name switch
        {
            "FromString" => TryGetStringLiteral(context, arguments[0].Expression),
            "FromBytes" => TryGetUtf8Literal(arguments[0].Expression),
            _ => null
        };

        if (string.IsNullOrEmpty(literal) || literal == "/")
            return null;

        return new LiteralMatch(literal);
    }

    private static string? TryGetStringLiteral(GeneratorSyntaxContext context, ExpressionSyntax expression)
    {
        var constantValue = context.SemanticModel.GetConstantValue(expression);
        return constantValue is { HasValue: true, Value: string value } ? value : null;
    }

    private static string? TryGetUtf8Literal(ExpressionSyntax expression)
    {
        return expression is LiteralExpressionSyntax literal &&
               literal.Token.Text.EndsWith("u8", StringComparison.Ordinal)
            ? literal.Token.ValueText
            : null;
    }

    private static void EmitRegistrationSource(SourceProductionContext context, Compilation compilation,
        System.Collections.Immutable.ImmutableArray<LiteralMatch> matches)
    {
        var distinctLiterals = matches
            .Select(static match => match.Value)
            .Where(static value => !string.IsNullOrEmpty(value))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static value => value, StringComparer.Ordinal)
            .ToArray();

        if (distinctLiterals.Length == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "FsNameLiterals";
        var typeSuffix = SanitizeIdentifier(assemblyName);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("namespace Fiberish.VFS;");
        builder.AppendLine();
        builder.Append("internal static class __FsNameLiteralRegistration_");
        builder.Append(typeSuffix);
        builder.AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");

        foreach (var literal in distinctLiterals)
        {
            builder.Append("        global::Fiberish.VFS.FsName.RegisterGeneratedLiteral(");
            builder.Append(SymbolDisplay.FormatLiteral(literal, quote: true));
            builder.AppendLine(");");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource($"FsNameLiteralRegistration.{typeSuffix}.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
            return "Generated";

        var builder = new StringBuilder(value.Length);
        if (!SyntaxFacts.IsIdentifierStartCharacter(value[0]))
            builder.Append('_');

        foreach (var ch in value)
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(ch) ? ch : '_');

        return builder.ToString();
    }

    private readonly record struct LiteralMatch(string Value);
}
