#include "ops_sse_int_impl.h"

namespace fiberish {
void RegisterSseIntOps() {
    using namespace op;
    g_Handlers[0x1DB] = DispatchWrapper<OpPand_Sse>;
    g_Handlers[0x1DF] = DispatchWrapper<OpPandn_Sse>;
    g_Handlers[0x1EB] = DispatchWrapper<OpPor_Sse>;
    g_Handlers[0x1EF] = DispatchWrapper<OpPxor_Sse>;
    g_Handlers[0x1FC] = DispatchWrapper<OpPaddb_Sse>;
    g_Handlers[0x1FD] = DispatchWrapper<OpPaddw_Sse>;
    g_Handlers[0x1FE] = DispatchWrapper<OpPaddd_Sse>;
    g_Handlers[0x1D4] = DispatchWrapper<OpPaddq_Sse>;
    g_Handlers[0x1F8] = DispatchWrapper<OpPsubb_Sse>;
    g_Handlers[0x1F9] = DispatchWrapper<OpPsubw_Sse>;
    g_Handlers[0x1FA] = DispatchWrapper<OpPsubd_Sse>;
    g_Handlers[0x1FB] = DispatchWrapper<OpPsubq_Sse>;
    g_Handlers[0x1F4] = DispatchWrapper<OpPmuludq_Sse>;
    g_Handlers[0x1F5] = DispatchWrapper<OpPmaddwd_Sse>;
    g_Handlers[0x174] = DispatchWrapper<OpPcmpeqb_Sse>;
    g_Handlers[0x175] = DispatchWrapper<OpPcmpeqw_Sse>;
    g_Handlers[0x176] = DispatchWrapper<OpPcmpeqd_Sse>;
    g_Handlers[0x164] = DispatchWrapper<OpPcmpgtb_Sse>;
    g_Handlers[0x165] = DispatchWrapper<OpPcmpgtw_Sse>;
    g_Handlers[0x166] = DispatchWrapper<OpPcmpgtd_Sse>;
    g_Handlers[0x1DE] = DispatchWrapper<OpPmaxub_Sse>;
    g_Handlers[0x1DA] = DispatchWrapper<OpPminub_Sse>;
    g_Handlers[0x1EE] = DispatchWrapper<OpPmaxsw_Sse>;
    g_Handlers[0x1EA] = DispatchWrapper<OpPminsw_Sse>;
    g_Handlers[0x1F1] = DispatchWrapper<OpPsllw_Sse>;
    g_Handlers[0x1F2] = DispatchWrapper<OpPslld_Sse>;
    g_Handlers[0x1F3] = DispatchWrapper<OpPsllq_Sse>;
    g_Handlers[0x1E1] = DispatchWrapper<OpPsraw_Sse>;
    g_Handlers[0x1E2] = DispatchWrapper<OpPsrad_Sse>;
    g_Handlers[0x1D1] = DispatchWrapper<OpPsrlw_Sse>;
    g_Handlers[0x1D2] = DispatchWrapper<OpPsrld_Sse>;
    g_Handlers[0x1D3] = DispatchWrapper<OpPsrlq_Sse>;
    g_Handlers[0x170] = DispatchWrapper<OpGroup_Pshuf>;
    g_Handlers[0x171] = DispatchWrapper<OpGroup_Sse_Shift_Imm_W>;
    g_Handlers[0x172] = DispatchWrapper<OpGroup_Sse_Shift_Imm_D>;
    g_Handlers[0x173] = DispatchWrapper<OpGroup_Sse_Shift_Imm_Q>;
    g_Handlers[0x168] = DispatchWrapper<OpPunpckhbw_Sse>;
    g_Handlers[0x169] = DispatchWrapper<OpPunpckhwd_Sse>;
    g_Handlers[0x16A] = DispatchWrapper<OpPunpckhdq_Sse>;
    g_Handlers[0x16D] = DispatchWrapper<OpPunpckhqdq_Sse>;
    g_Handlers[0x160] = DispatchWrapper<OpPunpcklbw_Sse>;
    g_Handlers[0x161] = DispatchWrapper<OpPunpcklwd_Sse>;
    g_Handlers[0x162] = DispatchWrapper<OpPunpckldq_Sse>;
    g_Handlers[0x16C] = DispatchWrapper<OpPunpcklqdq_Sse>;
    g_Handlers[0x163] = DispatchWrapper<OpPacksswb_Sse>;
    g_Handlers[0x16B] = DispatchWrapper<OpPackssdw_Sse>;
    g_Handlers[0x167] = DispatchWrapper<OpPackuswb_Sse>;
    g_Handlers[0x1D5] = DispatchWrapper<OpPmullw_Sse>;
    g_Handlers[0x1E5] = DispatchWrapper<OpPmulhw_Sse>;
    g_Handlers[0x1E4] = DispatchWrapper<OpPmulhuw_Sse>;
    g_Handlers[0x1DC] = DispatchWrapper<OpPaddusb_Sse>;
    g_Handlers[0x1DD] = DispatchWrapper<OpPaddusw_Sse>;
    g_Handlers[0x1EC] = DispatchWrapper<OpPaddsb_Sse>;
    g_Handlers[0x1ED] = DispatchWrapper<OpPaddsw_Sse>;
    g_Handlers[0x1D8] = DispatchWrapper<OpPsubusb_Sse>;
    g_Handlers[0x1D9] = DispatchWrapper<OpPsubusw_Sse>;
    g_Handlers[0x1E8] = DispatchWrapper<OpPsubsb_Sse>;
    g_Handlers[0x1E9] = DispatchWrapper<OpPsubsw_Sse>;
    g_Handlers[0x1E0] = DispatchWrapper<OpPavgb_Sse>;
    g_Handlers[0x1E3] = DispatchWrapper<OpPavgw_Sse>;
    g_Handlers[0x1F6] = DispatchWrapper<OpPsadbw_Sse>;
    g_Handlers[0x1C5] = DispatchWrapper<OpPextrw_Sse>;
    g_Handlers[0x1C4] = DispatchWrapper<OpPinsrw_Sse>;
    g_Handlers[0x1D7] = DispatchWrapper<OpPmovmskb_Sse>;
}

}  // namespace fiberish
