using System.Text;
using System.Xml.Linq;

namespace Podish.Wayland.Generator;

internal sealed record ProtocolModel(string Name, List<InterfaceModel> Interfaces);
internal sealed record InterfaceModel(string Name, uint Version, List<MessageModel> Requests, List<MessageModel> Events,
    List<EnumModel> Enums);
internal sealed record MessageModel(string Name, ushort Opcode, uint Since, List<ArgModel> Args);
internal sealed record ArgModel(string Name, string Type, string? Interface, bool AllowNull);
internal sealed record EnumModel(string Name, List<EnumEntryModel> Entries);
internal sealed record EnumEntryModel(string Name, string Value);

internal static class Program
{
    private static int Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.Error.WriteLine("Usage: Podish.Wayland.Generator <protocol.xml> [protocol.xml...]");
            return 1;
        }

        string repoRoot = FindRepoRoot();
        string outputDir = Path.Combine(repoRoot, "Podish.Wayland", "Generated");
        Directory.CreateDirectory(outputDir);

        foreach (string xmlPath in args)
        {
            ProtocolModel protocol = LoadProtocol(xmlPath);
            string outputPath = Path.Combine(outputDir, $"{Path.GetFileNameWithoutExtension(xmlPath)}.g.cs");
            File.WriteAllText(outputPath, RenderProtocol(protocol));
            Console.WriteLine($"Generated {outputPath}");
        }

        return 0;
    }

    private static ProtocolModel LoadProtocol(string xmlPath)
    {
        var document = XDocument.Load(xmlPath);
        XElement protocolElement = document.Root ?? throw new InvalidDataException("Protocol XML is missing a root.");
        string protocolName = protocolElement.Attribute("name")?.Value ?? Path.GetFileNameWithoutExtension(xmlPath);
        var interfaces = new List<InterfaceModel>();

        foreach (XElement iface in protocolElement.Elements("interface"))
        {
            string ifaceName = iface.Attribute("name")?.Value ?? throw new InvalidDataException("Interface without name.");
            uint version = uint.Parse(iface.Attribute("version")?.Value ?? "1");
            List<MessageModel> requests = ReadMessages(iface, "request");
            List<MessageModel> events = ReadMessages(iface, "event");
            var enums = iface.Elements("enum")
                .Select(e => new EnumModel(e.Attribute("name")?.Value ?? "unnamed",
                    e.Elements("entry")
                        .Select(entry => new EnumEntryModel(entry.Attribute("name")?.Value ?? "entry",
                            entry.Attribute("value")?.Value ?? "0"))
                        .ToList()))
                .ToList();
            interfaces.Add(new InterfaceModel(ifaceName, version, requests, events, enums));
        }

        return new ProtocolModel(protocolName, interfaces);
    }

    private static List<MessageModel> ReadMessages(XElement iface, string elementName)
    {
        var messages = new List<MessageModel>();
        ushort opcode = 0;
        foreach (XElement request in iface.Elements(elementName))
        {
            string name = request.Attribute("name")?.Value ?? throw new InvalidDataException($"Missing {elementName} name.");
            uint since = uint.Parse(request.Attribute("since")?.Value ?? "1");
            var args = request.Elements("arg")
                .Select(arg => new ArgModel(
                    arg.Attribute("name")?.Value ?? "arg",
                    arg.Attribute("type")?.Value ?? "uint",
                    arg.Attribute("interface")?.Value,
                    string.Equals(arg.Attribute("allow-null")?.Value, "true", StringComparison.OrdinalIgnoreCase)))
                .ToList();
            messages.Add(new MessageModel(name, opcode++, since, args));
        }

        return messages;
    }

    private static string RenderProtocol(ProtocolModel protocol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Podish.Wayland.Generator");
        sb.AppendLine($"// Source protocol: {protocol.Name}");
        sb.AppendLine("namespace Podish.Wayland;");
        sb.AppendLine();

        foreach (InterfaceModel iface in protocol.Interfaces)
        {
            string interfaceType = ToPascalCase(iface.Name);
            foreach (EnumModel enumModel in iface.Enums)
            {
                sb.AppendLine($"public enum {interfaceType}{ToPascalCase(enumModel.Name)} : uint");
                sb.AppendLine("{");
                foreach (EnumEntryModel entry in enumModel.Entries)
                    sb.AppendLine($"    {ToPascalCase(entry.Name)} = {entry.Value},");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            sb.AppendLine($"public static class {interfaceType}Protocol");
            sb.AppendLine("{");
            sb.AppendLine($"    public const string InterfaceName = \"{iface.Name}\";");
            sb.AppendLine($"    public const uint Version = {iface.Version};");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string ToPascalCase(string value)
    {
        return string.Concat(value.Split('_', '-', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
    }

    private static string FindRepoRoot()
    {
        string current = Directory.GetCurrentDirectory();
        while (!string.IsNullOrEmpty(current))
        {
            if (File.Exists(Path.Combine(current, "Fiberish.sln")))
                return current;
            current = Path.GetDirectoryName(current) ?? string.Empty;
        }

        throw new DirectoryNotFoundException("Could not locate repo root containing Fiberish.sln.");
    }
}
