using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Podish.PerfTools;

internal static partial class Program
{
    private static string GenerateSuperopcodes(string inputPath, int top, string workload = "", IReadOnlyList<string>? generationParams = null)
    {
        var data = JsonDocument.Parse(File.ReadAllText(inputPath, Encoding.UTF8)).RootElement;
        var candidates =
            new List<(string Op0, string Op1, long Wec, long Occ, string Relation, string Anchor, string Direction)>();
        generationParams ??= Array.Empty<string>();

        if (data.TryGetProperty("candidates", out var candidatesNode) &&
            candidatesNode.ValueKind == JsonValueKind.Array)
        {
            var seen = new HashSet<(string, string)>();
            foreach (var candidate in candidatesNode.EnumerateArray())
            {
                var pair = candidate.TryGetProperty("pair", out var pairNode) &&
                           pairNode.ValueKind == JsonValueKind.Array
                    ? pairNode.EnumerateArray().Select(e => e.GetString() ?? "").ToArray()
                    : Array.Empty<string>();
                if (pair.Length != 2)
                    continue;

                var op0 = CanonicalLogicName(pair[0]);
                var op1 = CanonicalLogicName(pair[1]);
                if (op0 is null || op1 is null)
                    continue;

                if (!seen.Add((op0, op1)))
                    continue;

                candidates.Add((
                    op0,
                    op1,
                    candidate.TryGetProperty("weighted_exec_count", out var wec) ? wec.GetInt64() : 0,
                    candidate.TryGetProperty("occurrences", out var occ) ? occ.GetInt64() : 0,
                    candidate.TryGetProperty("relation_kind", out var rel) ? rel.GetString() ?? "" : "",
                    candidate.TryGetProperty("anchor_display", out var anchor) ? anchor.GetString() ?? "" : "",
                    candidate.TryGetProperty("direction", out var dir) ? dir.GetString() ?? "" : ""));

                if (candidates.Count >= top)
                    break;
            }
        }

        var implIncludes = Directory.EnumerateFiles(Path.Combine("libfibercpu", "src", "ops"), "*_impl.h")
            .OrderBy(x => x, StringComparer.Ordinal)
            .Select(file => $"#include \"../ops/{Path.GetFileName(file)}\"");

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Podish.PerfTools gen-superopcodes.");
        sb.AppendLine($"// source_input={SanitizeCommentPath(inputPath)}");
        if (!string.IsNullOrWhiteSpace(workload))
            sb.AppendLine($"// workload={workload}");
        if (generationParams.Count > 0)
            sb.AppendLine($"// generation_params={string.Join(' ', generationParams.Select(SanitizeCommentArgument))}");
        AppendMetadataComment(sb, data, "inputs", "candidate_inputs");
        AppendMetadataComment(sb, data, "score_basis");
        AppendMetadataComment(sb, data, "raw_weight");
        AppendMetadataComment(sb, data, "rar_weight");
        AppendMetadataComment(sb, data, "waw_weight");
        AppendMetadataComment(sb, data, "jcc_multiplier");
        AppendMetadataComment(sb, data, "jcc_mode");
        AppendMetadataComment(sb, data, "min_samples");
        AppendMetadataComment(sb, data, "min_weighted_exec_count");
        AppendMetadataComment(sb, data, "top_limit", "candidate_top_limit");
        sb.AppendLine($"// generated_superopcode_top={top}");
        sb.AppendLine($"// generated_candidate_count={candidates.Count}");
        sb.AppendLine("#include <ankerl/unordered_dense.h>");
        sb.AppendLine("#include <atomic>");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("#include \"../superopcodes.h\"");
        sb.AppendLine("#include \"../ops.h\"");
        foreach (var include in implIncludes)
            sb.AppendLine(include);
        sb.AppendLine();
        sb.AppendLine("namespace fiberish {");
        sb.AppendLine();
        sb.AppendLine("namespace {");
        sb.AppendLine("struct GeneratedSuperOpcodeKey {");
        sb.AppendLine("    HandlerFunc op0;");
        sb.AppendLine("    HandlerFunc op1;");
        sb.AppendLine();
        sb.AppendLine("    bool operator==(const GeneratedSuperOpcodeKey& other) const = default;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("struct GeneratedSuperOpcodeKeyHash {");
        sb.AppendLine("    auto operator()(const GeneratedSuperOpcodeKey& key) const -> uint64_t {");
        sb.AppendLine("        auto mix = [](uint64_t value) -> uint64_t {");
        sb.AppendLine("            value ^= value >> 33;");
        sb.AppendLine("            value *= 0xff51afd7ed558ccdULL;");
        sb.AppendLine("            value ^= value >> 33;");
        sb.AppendLine("            value *= 0xc4ceb9fe1a85ec53ULL;");
        sb.AppendLine("            value ^= value >> 33;");
        sb.AppendLine("            return value;");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        uint64_t h0 = mix(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(key.op0)));");
        sb.AppendLine("        uint64_t h1 = mix(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(key.op1)));");
        sb.AppendLine("        return h0 ^ (h1 + 0x9e3779b97f4a7c15ULL + (h0 << 6) + (h0 >> 2));");
        sb.AppendLine("    }");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("using GeneratedSuperOpcodeTable =");
        sb.AppendLine("    ankerl::unordered_dense::map<GeneratedSuperOpcodeKey, HandlerFunc, GeneratedSuperOpcodeKeyHash>;");
        sb.AppendLine();
        sb.AppendLine("}  // namespace");
        sb.AppendLine();

        for (var index = 0; index < candidates.Count; index++)
        {
            var c = candidates[index];
            var handlerName = $"SuperOpcode_{index:000}_{SanitizeName(c.Op0[4..])}__{SanitizeName(c.Op1[4..])}";
            sb.AppendLine(
                $"// weighted_exec_count={c.Wec} occurrences={c.Occ} relation={c.Relation} anchor={c.Anchor} direction={c.Direction}");
            sb.AppendLine("ATTR_PRESERVE_NONE int64_t " + handlerName +
                          "(EmuState* RESTRICT state, DecodedOp* RESTRICT op, int64_t instr_limit,");
            sb.AppendLine(
                "                                          mem::MicroTlbAbiWord utlb_tags, mem::MicroTlbAbiWord utlb_addend,");
            sb.AppendLine("                                          uint32_t branch, uint64_t flags_cache) {");
            sb.AppendLine("    mem::MicroTLB utlb = mem::DecodeMicroTlbAbi(utlb_tags, utlb_addend);");
            sb.AppendLine($"    RUN_SUPEROPCODE_OP({c.Op0}, state, op, instr_limit, utlb, branch, flags_cache);");
            sb.AppendLine();
            sb.AppendLine("    DecodedOp* second_op = NextOp(op);");
            sb.AppendLine(
                $"    RUN_SUPEROPCODE_OP({c.Op1}, state, second_op, instr_limit, utlb, branch, flags_cache);");
            sb.AppendLine();
            sb.AppendLine("    if (auto* next_op = NextOp(second_op)) {");
            sb.AppendLine(
                "        mem::EncodeMicroTlbAbi(utlb, utlb_tags, utlb_addend);");
            sb.AppendLine(
                "        ATTR_MUSTTAIL return next_op->handler(state, next_op, instr_limit, utlb_tags, utlb_addend, branch, flags_cache);");
            sb.AppendLine("    }");
            sb.AppendLine("    __builtin_unreachable();");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("namespace {");
        sb.AppendLine("GeneratedSuperOpcodeTable* BuildGeneratedSuperOpcodeTable() {");
        sb.AppendLine("    auto* table = new GeneratedSuperOpcodeTable();");
        sb.AppendLine($"    table->reserve({candidates.Count});");
        for (var index = 0; index < candidates.Count; index++)
        {
            var c = candidates[index];
            var handlerName = $"SuperOpcode_{index:000}_{SanitizeName(c.Op0[4..])}__{SanitizeName(c.Op1[4..])}";
            sb.AppendLine(
                $"    table->emplace(GeneratedSuperOpcodeKey{{(HandlerFunc)DispatchWrapper<{c.Op0}>, (HandlerFunc)DispatchWrapper<{c.Op1}>}}, {handlerName});");
        }
        sb.AppendLine("    return table;");
        sb.AppendLine("}");
        sb.AppendLine("}  // namespace");
        sb.AppendLine();

        sb.AppendLine("__attribute__((used)) HandlerFunc GeneratedFindSuperOpcode(const DecodedOp* ops) {");
        sb.AppendLine("    if (!ops) return nullptr;");
        sb.AppendLine("    static std::atomic<GeneratedSuperOpcodeTable*> table_ptr{nullptr};");
        sb.AppendLine("    auto* table = table_ptr.load(std::memory_order_acquire);");
        sb.AppendLine("    if (!table) {");
        sb.AppendLine("        auto* new_table = BuildGeneratedSuperOpcodeTable();");
        sb.AppendLine("        auto* expected = static_cast<GeneratedSuperOpcodeTable*>(nullptr);");
        sb.AppendLine("        if (!table_ptr.compare_exchange_strong(expected, new_table, std::memory_order_acq_rel,");
        sb.AppendLine("                                               std::memory_order_acquire)) {");
        sb.AppendLine("            delete new_table;");
        sb.AppendLine("            table = expected;");
        sb.AppendLine("        } else {");
        sb.AppendLine("            table = new_table;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    auto it = table->find(GeneratedSuperOpcodeKey{ops[0].handler, ops[1].handler});");
        sb.AppendLine("    return it != table->end() ? it->second : nullptr;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("}  // namespace fiberish");

        return sb.ToString();
    }

    private static string SanitizeCommentArgument(string arg)
    {
        int separator = arg.IndexOf('=');
        if (separator <= 0)
            return SanitizeCommentPath(arg);

        string key = arg[..(separator + 1)];
        string value = arg[(separator + 1)..];
        return key + SanitizeCommentPath(value);
    }

    private static string SanitizeCommentPath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return path;

        string fullPath = Path.GetFullPath(path);
        string repoRoot = Path.GetFullPath(Directory.GetCurrentDirectory());
        if (fullPath.StartsWith(repoRoot, StringComparison.Ordinal))
            return Path.GetRelativePath(repoRoot, fullPath).Replace('\\', '/');
        return path;
    }

    private static void AppendMetadataComment(StringBuilder sb, JsonElement root, string metadataKey, string? commentKey = null)
    {
        if (!root.TryGetProperty("metadata", out var metadata) || metadata.ValueKind != JsonValueKind.Object)
            return;
        if (!metadata.TryGetProperty(metadataKey, out var value))
            return;

        var rendered = value.ValueKind switch
        {
            JsonValueKind.Array => string.Join(", ", value.EnumerateArray().Select(RenderJsonElementForComment)),
            _ => RenderJsonElementForComment(value)
        };
        if (string.IsNullOrWhiteSpace(rendered))
            return;

        sb.AppendLine($"// {commentKey ?? metadataKey}={rendered}");
    }

    private static string RenderJsonElementForComment(JsonElement value)
    {
        return value.ValueKind switch
        {
            JsonValueKind.String => SanitizeCommentPath(value.GetString() ?? ""),
            JsonValueKind.Number => value.GetRawText(),
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Null => "",
            _ => value.GetRawText()
        };
    }

    private static string CanonicalLogicName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "";
        if (name.StartsWith("op::Op", StringComparison.Ordinal))
            return name;
        if (name.StartsWith("Op", StringComparison.Ordinal))
            return "op::" + name;
        return "";
    }

    private static string SanitizeName(string name)
    {
        return Regex.Replace(name, "[^A-Za-z0-9_]", "_");
    }
}
