import sys
import subprocess
import re
import os
import argparse
import json

def normalize_input_paths(raw_paths):
    paths = []
    for raw in raw_paths:
        for part in raw.split(";"):
            part = part.strip()
            if part:
                paths.append(part)
    return paths

def generate(input_paths, out_cpp_path, mode, usage_path=None):
    input_paths = normalize_input_paths(input_paths)
    print(f"Scanning {len(input_paths)} input files for op::* targets...")
    for p in input_paths:
        print(f"  Input: {p}")
        
    targets = []
    # Match symbols like _ZNS_2op10OpAdc_EbGbEPNS_8EmuState... or inside DispatchWrapper
    symbol_regex = re.compile(r'_ZNS_2op(\d+)(Op[A-Za-z0-9_]+)EPNS_8EmuState')
    
    for path in input_paths:
        if not os.path.exists(path):
            print(f"Warning: input path {path} does not exist")
            continue
        res = subprocess.run(["nm", "-j", path], capture_output=True, text=True)
        if res.returncode != 0:
            print(f"Warning: nm failed for {path}")
            continue
        
        count_before = len(targets)
        for line in res.stdout.splitlines():
            line = line.strip()
            m = symbol_regex.search(line)
            if m:
                func_name = m.group(2)
                if func_name not in targets:
                    targets.append(func_name)
        if len(targets) > count_before:
            print(f"    Found {len(targets) - count_before} targets in {path}")
    
    usage_data = {}
    if mode == "stencil" and usage_path and os.path.exists(usage_path):
        with open(usage_path, "r") as f:
            usage_data = json.load(f)

    print(f"Total found: {len(targets)} op::* targets. Generating {mode} code to {out_cpp_path}...")

    # Find all ops/*_impl.h files
    search_dirs = [
        "libfibercpu/ops",
        "../libfibercpu/ops",
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "../libfibercpu/ops")
    ]
    ops_dir = None
    for d in search_dirs:
        if os.path.exists(d):
            ops_dir = d
            break

    impl_headers = []
    if ops_dir:
        for f_name in os.listdir(ops_dir):
            if f_name.endswith("_impl.h"):
                impl_headers.append(f"ops/{f_name}")

    with open(out_cpp_path, "w") as f:
        f.write('// Auto-generated by gen_jit_stencils.py\n')
        f.write('#include "jit/stencil.h"\n')
        f.write('#include "decoder.h"\n')
        f.write('#include "dispatch.h"\n')
        f.write('\n')
        
        for header in sorted(impl_headers):
            f.write(f'#include "{header}"\n')
                
        f.write('\nnamespace fiberish::jit {\n\n')

        if mode == "stencil":
            f.write('enum class JitMemReplayResult : uint8_t {\n')
            f.write('    Fault,\n')
            f.write('    RestartOp,\n')
            f.write('    ContinueNext,\n')
            f.write('};\n\n')
            f.write('template <bool RestartCurrentOp>\n')
            f.write('inline JitMemReplayResult ReplayPendingMemOp(EmuState* RESTRICT state,\n')
            f.write('                                        DecodedOp* RESTRICT runtime_op,\n')
            f.write('                                        mem::MicroTLB* utlb) {\n')
            f.write('    (void)runtime_op;\n')
            f.write('    bool fault = false;\n')
            f.write('    auto execute_mem_op = [&]<typename T>(uint32_t addr, T* value, bool is_write) {\n')
            f.write('        if (!is_write) {\n')
            f.write('            auto res = state->mmu.read<T>(addr, utlb, runtime_op);\n')
            f.write('            if (!res) fault = true;\n')
            f.write('            else *value = *res;\n')
            f.write('        } else {\n')
            f.write('            if (!state->mmu.write<T>(addr, *value, utlb, runtime_op)) fault = true;\n')
            f.write('        }\n')
            f.write('    };\n')
            f.write('    auto perform = [&](uint32_t addr, uint32_t size, std::byte* value, bool is_write) {\n')
            f.write('        struct TSize10 { std::byte data[10]; };\n')
            f.write('        struct TSize16 { std::byte data[16]; };\n')
            f.write('        switch (size) {\n')
            f.write('            case 1: execute_mem_op(addr, reinterpret_cast<uint8_t*>(value), is_write); break;\n')
            f.write('            case 2: execute_mem_op(addr, reinterpret_cast<uint16_t*>(value), is_write); break;\n')
            f.write('            case 4: execute_mem_op(addr, reinterpret_cast<uint32_t*>(value), is_write); break;\n')
            f.write('            case 8: execute_mem_op(addr, reinterpret_cast<uint64_t*>(value), is_write); break;\n')
            f.write('            case 10: execute_mem_op(addr, reinterpret_cast<TSize10*>(value), is_write); break;\n')
            f.write('            case 16: execute_mem_op(addr, reinterpret_cast<TSize16*>(value), is_write); break;\n')
            f.write('            default: __builtin_unreachable();\n')
            f.write('        }\n')
            f.write('    };\n')
            f.write('    std::visit([&](auto&& arg) {\n')
            f.write('        using T = std::decay_t<decltype(arg)>;\n')
            f.write('        if constexpr (std::is_same_v<T, std::monostate>) {\n')
            f.write('        } else if constexpr (std::is_same_v<T, MemReadOperation>) {\n')
            f.write('            perform(arg.addr, arg.size, arg.data.data(), false);\n')
            f.write('            if (!fault) arg.done = true;\n')
            f.write('        } else if constexpr (std::is_same_v<T, MemWriteOperation>) {\n')
            f.write('            perform(arg.addr, arg.size, arg.data.data(), true);\n')
            f.write('            if (!fault) arg.done = true;\n')
            f.write('        }\n')
            f.write('    }, state->mem_op);\n')
            f.write('    if (fault) {\n')
            f.write('        state->mem_op.emplace<0>();\n')
            f.write('        return JitMemReplayResult::Fault;\n')
            f.write('    }\n')
            f.write('    if constexpr (RestartCurrentOp) return JitMemReplayResult::RestartOp;\n')
            f.write('    state->mem_op.emplace<0>();\n')
            f.write('    return JitMemReplayResult::ContinueNext;\n')
            f.write('}\n\n')
        
        if mode == "probe":
            f.write('template <LogicFunc Target>\n')
            f.write('__attribute__((noinline, used)) ATTR_PRESERVE_NONE int64_t\n')
            f.write('ProbeKernel(EmuState* RESTRICT state,\n')
            f.write('            DecodedOp* RESTRICT op,\n')
            f.write('            int64_t instr_limit,\n')
            f.write('            mem::MicroTLB utlb,\n')
            f.write('            uint32_t branch,\n')
            f.write('            uint64_t flags_cache) {\n')
            f.write('    auto flow = Target(state, op, &utlb, GetImm(op), &branch, flags_cache);\n')
            f.write('    if (flow == LogicFlow::Continue) return instr_limit ^ static_cast<int64_t>(flags_cache);\n')
            f.write('    if (flow == LogicFlow::ExitToBranch) return static_cast<int64_t>(branch) ^ 0x4000000000000000LL;\n')
            f.write('    return -1;\n')
            f.write('}\n\n')
            
            for target in targets:
                f.write(f'extern "C" __attribute__((used)) ATTR_PRESERVE_NONE int64_t ')
                f.write(f'JitProbe_{target}(EmuState* s, DecodedOp* o, int64_t l, mem::MicroTLB u, uint32_t b, uint64_t f) {{\n')
                f.write(f'    return ProbeKernel<op::{target}>(s, o, l, u, b, f);\n')
                f.write(f'}}\n\n')

        else:
            field_params = [
                "UseQword1", "UseQword2", "UseQword3"
            ]
            params = ", ".join([f"bool {p}" for p in field_params])

            f.write(f'template <LogicFunc Target, {params}>\n')
            f.write('__attribute__((noinline, used)) ATTR_PRESERVE_NONE int64_t\n')
            f.write('JitDispatchKernel(EmuState* RESTRICT state,\n')
            f.write('                  DecodedOp* RESTRICT decoded_op,\n')
            f.write('                  int64_t instr_limit,\n')
            f.write('                  mem::MicroTLB utlb,\n')
            f.write('                  uint32_t branch,\n')
            f.write('                  uint64_t flags_cache) {\n')
            f.write('    DecodedOp* runtime_op = decoded_op;\n')
            f.write('    DecodedOp op{};\n')
            
            f.write('    if constexpr (UseQword1) *reinterpret_cast<uint64_t*>(reinterpret_cast<uint8_t*>(&op) + 8) = PatchMagic64<PatchKind::OpQword64, 1>();\n')
            f.write('    if constexpr (UseQword2) *reinterpret_cast<uint64_t*>(reinterpret_cast<uint8_t*>(&op) + 16) = PatchMagic64<PatchKind::OpQword64, 2>();\n')
            f.write('    if constexpr (UseQword3) *reinterpret_cast<uint64_t*>(reinterpret_cast<uint8_t*>(&op) + 24) = PatchMagic64<PatchKind::OpQword64, 3>();\n')
            
            f.write('\n    PREFETCH(reinterpret_cast<const std::byte*>(runtime_op) + 128);\n')
            f.write('    PREFETCH(reinterpret_cast<const std::byte*>(runtime_op) + 256);\n')
            f.write('\n    for (;;) {\n')
            f.write('        auto flow = Target(state, &op, &utlb, GetImm(&op), &branch, flags_cache);\n')
            f.write('        switch (flow) {\n')
            f.write('            case LogicFlow::Continue:\n')
            f.write('                if (auto* next_runtime_op = NextOp(runtime_op)) {\n')
            f.write('                    ATTR_MUSTTAIL return JitContinueTarget(state, next_runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('                }\n')
            f.write('                __builtin_unreachable();\n')
            f.write('            case LogicFlow::ContinueSkipOne:\n')
            f.write('                if (auto* next_runtime_op = NextOp(NextOp(runtime_op))) {\n')
            f.write('                    ATTR_MUSTTAIL return JitContinueSkipOneTarget(state, next_runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('                }\n')
            f.write('                __builtin_unreachable();\n')
            f.write('            case LogicFlow::ExitOnCurrentEIP:\n')
            f.write('                ATTR_MUSTTAIL return JitExitOnCurrentEipTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('            case LogicFlow::ExitOnNextEIP:\n')
            f.write('                ATTR_MUSTTAIL return JitExitOnNextEipTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('            case LogicFlow::RestartMemoryOp: {\n')
            f.write('                auto replay = ReplayPendingMemOp<true>(state, runtime_op, &utlb);\n')
            f.write('                if (replay == JitMemReplayResult::RestartOp) continue;\n')
            f.write('                if (replay == JitMemReplayResult::Fault) {\n')
            f.write('                    ATTR_MUSTTAIL return JitFaultExitTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('                }\n')
            f.write('                __builtin_unreachable();\n')
            f.write('            }\n')
            f.write('            case LogicFlow::RetryMemoryOp: {\n')
            f.write('                auto replay = ReplayPendingMemOp<false>(state, runtime_op, &utlb);\n')
            f.write('                if (replay == JitMemReplayResult::Fault) {\n')
            f.write('                    ATTR_MUSTTAIL return JitFaultExitTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('                }\n')
            f.write('                if (auto* next_runtime_op = NextOp(runtime_op)) {\n')
            f.write('                    ATTR_MUSTTAIL return JitContinueTarget(state, next_runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('                }\n')
            f.write('                __builtin_unreachable();\n')
            f.write('            }\n')
            f.write('            case LogicFlow::ExitToBranch:\n')
            f.write('                ATTR_MUSTTAIL return ResolveBranchTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('            default:\n')
            f.write('                ATTR_MUSTTAIL return JitExitDefaultTarget(state, runtime_op, instr_limit, utlb, branch, flags_cache);\n')
            f.write('        }\n')
            f.write('    }\n')
            f.write('}\n\n')

            for target in targets:
                mask = usage_data.get(target, {})
                vals = []
                field_keys = [
                    bool(mask.get("qword1")),
                    bool(mask.get("qword2")),
                    bool(mask.get("qword3")),
                ]
                for used in field_keys:
                    vals.append("true" if used else "false")
                
                f.write(f'extern "C" __attribute__((used)) ATTR_PRESERVE_NONE int64_t ')
                f.write(f'JitStencilExt_{target}(EmuState* s, DecodedOp* o, int64_t l, mem::MicroTLB u, uint32_t b, uint64_t f) {{\n')
                f.write(f'    return JitDispatchKernel<op::{target}, {", ".join(vals)}>(s, o, l, u, b, f);\n')
                f.write(f'}}\n')
                f.write(f'extern "C" HandlerFunc JitStencilHandler_{target} = DispatchWrapper<op::{target}>;\n\n')

        f.write('\n} // namespace fiberish::jit\n')

if __name__ == "__main__":
    mode = "stencil"
    usage = None
    inputs = []
    
    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg.startswith("--mode="):
            mode = arg.split("=", 1)[1]
        elif arg.startswith("--usage="):
            usage = arg.split("=", 1)[1]
        elif arg == "--mode":
            mode = sys.argv[i+1]
            i += 1
        elif arg == "--usage":
            usage = sys.argv[i+1]
            i += 1
        else:
            inputs.append(arg)
        i += 1
        
    if len(inputs) < 2:
        print("Usage: gen_jit_stencils.py [--mode=...] [--usage=...] <inputs...> <output>")
        sys.exit(1)
        
    output = inputs.pop()
    generate(inputs, output, mode, usage)
